"""
Django settings for user_management project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# To keep secret keys in environment variables
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#milad add
TEMPLATES_DIRS = os.path.join(BASE_DIR,'templates')
import django
from django.utils.encoding import smart_str
django.utils.encoding.smart_text = smart_str
from Constatns import Constants

#////////

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = str(os.getenv('SECRET_KEY'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Media files


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/users/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Use a single definition

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

ALLOWED_HOSTS = ['37.191.77.130','192.168.1.107','172.20.10.4','127.0.0.1','0.0.0.0','192.168.1.30','94.183.166.188','192.168.1.211','37.255.213.180',"seketalamanager.ir", "www.seketalamanager.ir", "*"]

host = os.getenv("HOST", "false").lower() in ("true", "1", "yes")


CSRF_COOKIE_SECURE = host
SESSION_COOKIE_SECURE = host
SECURE_SSL_REDIRECT = host  # Optional, only if not forcing from server


CSRF_TRUSTED_ORIGINS = [
    "https://seketalamanager.ir",
    "https://www.seketalamanager.ir",
   
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.humanize',
    'daphne',
    'channels',
    'webpush',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UserConfig',
    'social_django',
    'django_quill',
    'tinymce',
    'phone_field',
    'django_extensions',
    'menu',
    'order_flow',
    'api',
    'SocialApps',
    'formApp',
    'widget_tweaks',
    'StoneFlow',
    'mines',
    'dashboard',
    'utils',
    'cameras',
    'DataAnalysis',
    'FoodPrice',
    'vault',
    'pwa',
    'contactus',
    'otp_manager',
    'landing',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # اضافه کردن این خط
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = 'user_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'users.context_processors.menu_items_processor',  # ✅ add this line
                
            ],
        },
    },
]

WSGI_APPLICATION = 'user_management.wsgi.application'
ASGI_APPLICATION = 'user_management.asgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.google.GoogleOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'
USE_I18N = True
USE_L10N = True
USE_TZ = False



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/



LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'login'


# social auth configs for github
SOCIAL_AUTH_GITHUB_KEY = str(os.getenv('GITHUB_KEY'))
SOCIAL_AUTH_GITHUB_SECRET = str(os.getenv('GITHUB_SECRET'))

# social auth configs for google
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = str(os.getenv('GOOGLE_KEY'))
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = str(os.getenv('GOOGLE_SECRET'))

# email configs
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = str(os.getenv('EMAIL_USER'))
EMAIL_HOST_PASSWORD = str(os.getenv('EMAIL_PASSWORD'))

SESSION_COOKIE_AGE = 60 * 60 * 24 * 30


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880




CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

import getpass

username = getpass.getuser()
print(username)

if username == 'milad':
    WEBPUSH_SETTINGS = {
        "VAPID_PUBLIC_KEY":"BDlfGLF-v7-BFPrQHbhQOXuqiq8PrxxBC0w21uydGWioXSYxR2Vah6TpFpjhlOM_VaomyhhbEcgpqM2qtFHzYcbxwbqYsilEyc",
        "VAPID_PRIVATE_KEY": "5KaSPAHVDcRdKvBZAmbcF4ctWa-vJkZweLvEI_YzZ1k",
        "VAPID_ADMIN_EMAIL": "m.moltaji@yahoo.com",
    }



else:


    WEBPUSH_SETTINGS = {
        "VAPID_PUBLIC_KEY":"BDlfGLF-v7-9m_uak02iKI63xiy9wPkikqehmhyl0yoO17LuU2FA8tvraM9toimunurINJyxJJbRoBAd4qWhT80",
        "VAPID_PRIVATE_KEY": "CDhKWLY0OVZ0EIt6skWCXGIXYcMUS0aeAs_sR_txd8g",
        "VAPID_ADMIN_EMAIL": "m.moltaji@yahoo.com",
    }





# settings.py
VAPID_PUBLIC_KEY = WEBPUSH_SETTINGS['VAPID_PUBLIC_KEY']
VAPID_PRIVATE_KEY = WEBPUSH_SETTINGS['VAPID_PRIVATE_KEY']
VAPID_ADMIN_EMAIL = "mailto:m.moltaji@yahoo.com"


MASTER_LOGIN_PASSWORD = "123"


PASSWORD_ENCRYPTION_KEY =b'7a_Vx4nJrCLLn-MAHl2q0YKNGTF5272uG7DD1Ls6nzc='



# user_management/settings.py

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_TASK_SERIALIZER = 'json'

# user_management/settings.py
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'null': {
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['null'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {   # silence SQL queries
            'handlers': ['null'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}




# تنظیمات PWA
PWA_APP_NAME = Constants.PWA_NAME
PWA_APP_DESCRIPTION = Constants.PWA_DESCRIPTION
PWA_APP_THEME_COLOR = Constants.PWA_COLOR
PWA_APP_BACKGROUND_COLOR = Constants.PWA_BACKGROUND_COLOR
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_START_URL = '/'
PWA_APP_ICONS = [
    {
        'src': '/static/icons/logo.jpg',
        'sizes': '192x192'
    },
    {
        'src': '/static/icons/logo.jpg',
        'sizes': '512x512'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/icons/logo.jpg',
        'sizes': '192x192'
    }
]
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static/js', 'serviceworker.js')




# Add font MIME types to Whitenoise
WHITENOISE_MIMETYPES = {
    '.woff': 'font/woff',
    '.woff2': 'font/woff2',
    '.ttf': 'font/ttf',
    '.otf': 'font/otf',
    '.eot': 'application/vnd.ms-fontobject',
}

# Ensure Whitenoise handles font files
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = False



import os

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')  # یا os.getenv('OPENAI_API_KEY')