# Generated by Django 5.2.6 on 2025-11-21 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodPrice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodingredient',
            name='raw_material',
        ),
        migrations.AddField(
            model_name='foodingredient',
            name='raw_material_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_foods', to='FoodPrice.rawmaterialprice'),
            preserve_default=False,
        ),
    ]
