# Generated by Django 5.2.6 on 2025-11-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodPrice', '0002_remove_foodingredient_raw_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialprice',
            name='newest_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawmaterialprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
