# Generated by Django 5.1.1 on 2025-02-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialusage',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
