# Generated by Django 5.0.7 on 2024-10-10 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_allowedlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedlocation',
            name='locations',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
    ]
