# Generated by Django 5.0.7 on 2024-10-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_allowedlocation_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedlocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='allowedlocation',
            name='longitude',
        ),
    ]
