# Generated by Django 5.0.7 on 2024-10-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_alter_allowedlocation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedlocation',
            name='radius_meters',
        ),
        migrations.AddField(
            model_name='location',
            name='radius_meters',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
