# Generated by Django 5.0.7 on 2024-10-13 16:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_remove_allowedlocation_radius_meters_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryexitlog',
            name='entry_time',
        ),
        migrations.RemoveField(
            model_name='entryexitlog',
            name='exit_time',
        ),
        migrations.AddField(
            model_name='entryexitlog',
            name='is_entry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entryexitlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entryexitlog',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Entry_locations', to='users.location'),
        ),
        migrations.AlterField(
            model_name='entryexitlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Entry_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
