# Generated by Django 5.1.1 on 2025-02-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_inventory_level_inputreceipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='level',
            new_name='Receipt_Number',
        ),
    ]
