# Generated by Django 5.1.1 on 2025-02-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_rename_level_inventory_receipt_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='Receipt_Number',
            new_name='receipt_Number',
        ),
    ]
