# Generated by Django 5.1.1 on 2025-02-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_rename_receipt_number_inventory_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='receipt_Number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
