# Generated by Django 5.1.1 on 2025-02-09 22:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_capturedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedimage',
            name='receipt_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
