# Generated by Django 5.1.1 on 2025-02-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_capturedimage_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrawmaterial',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
