# Generated by Django 5.1.1 on 2025-02-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_foodrawmaterial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrawmaterial',
            name='details',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
