# Generated by Django 5.1.1 on 2025-02-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_foodrawmaterial_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrawmaterial',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
