# Generated by Django 5.1.1 on 2025-02-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_soldoutstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoldOutStatus',
        ),
    ]
