# Generated by Django 5.1.1 on 2025-02-17 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_delete_soldoutstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='users.raw_material')),
                ('main_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='users.raw_material')),
            ],
        ),
    ]
