# Generated by Django 5.1.1 on 2025-02-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_materialcomposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcomposition',
            name='quantity',
            field=models.FloatField(blank=True),
        ),
    ]
