# Generated by Django 5.1.1 on 2025-02-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_alter_materialcomposition_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcomposition',
            name='quantity',
            field=models.FloatField(blank=True, default=True),
        ),
    ]
