# Generated by Django 5.1.1 on 2025-02-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_alter_materialcomposition_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcomposition',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
    ]
