# Generated by Django 5.1.1 on 2025-02-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_alter_materialcomposition_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialcomposition',
            old_name='quantity',
            new_name='ratio',
        ),
    ]
