# Generated by Django 5.1.1 on 2025-02-17 21:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0083_rename_quantity_materialcomposition_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcomposition',
            name='has_discard',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produced_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discarded_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='users.materialcomposition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='users.profile')),
            ],
        ),
    ]
