# Generated by Django 5.1.1 on 2025-03-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_remainingmaterialsusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrawmaterial',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
