# Generated by Django 5.1.1 on 2025-03-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_foodrawmaterial_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='push_auth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='push_endpoint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='push_p256dh',
            field=models.TextField(blank=True, null=True),
        ),
    ]
