# Generated by Django 5.1.1 on 2025-04-03 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0088_sms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMS',
        ),
    ]
