# Generated by Django 5.1.1 on 2025-05-30 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0091_buyer_inventorylog_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ملیت')),
            ],
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='created_at',
        ),
        migrations.AddField(
            model_name='buyer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='nation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='نام '),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='نام نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='national_code',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nationality', verbose_name='ملیت'),
        ),
    ]
