# Generated by Django 5.1.1 on 2025-05-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0092_nationality_remove_buyer_created_at_buyer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام نام خانوادگی'),
        ),
    ]
