# Generated by Django 5.1.1 on 2025-05-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0094_buyer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='confirmed_by_buyer',
            field=models.BooleanField(default=False),
        ),
    ]
