# Generated by Django 5.1.1 on 2025-06-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0096_reporttitles_dailyreports'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='gender',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن'), ('unknown', 'اطلاع ندارم')], default='unknown', max_length=10, verbose_name='جنسیت'),
        ),
    ]
