# Generated by Django 5.1.1 on 2025-06-23 01:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_buyer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
