# Generated by Django 5.2.3 on 2025-06-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0098_buyer_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mother_material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mother_material_image/'),
        ),
        migrations.AddField(
            model_name='raw_material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='raw_material_image/'),
        ),
    ]
