# Generated by Django 5.1.1 on 2025-07-17 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0099_mother_material_image_raw_material_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان نحوه آشنایی')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='عنوان ویژگی')),
                ('field_type', models.CharField(choices=[('text', 'متن'), ('number', 'عدد'), ('date', 'تاریخ'), ('price', 'قیمت'), ('image', 'تصویر')], max_length=20, verbose_name='نوع فیلد')),
                ('required', models.BooleanField(default=False, verbose_name='ضروری است')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True, verbose_name='مقدار ویژگی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='buyer_attrs/', verbose_name='تصویر')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.buyerattribute')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='users.buyer')),
            ],
        ),
        migrations.AddField(
            model_name='buyer',
            name='introduction_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.introductionmethod', verbose_name='نحوه آشنایی'),
        ),
    ]
