# Generated by Django 5.2.4 on 2025-07-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0102_menuitem_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='roles', to='users.menuitem', verbose_name='دسترسی به آیتم\u200cها'),
        ),
    ]
