# Generated by Django 5.2.4 on 2025-07-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0103_jobs_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='items',
        ),
    ]
