# Generated by Django 5.2.4 on 2025-07-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0105_alter_profile_bio_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_position',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
