# Generated by Django 5.2.4 on 2025-07-22 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0106_alter_profile_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_job_position', to='users.jobs'),
        ),
    ]
