# Generated by Django 5.2.4 on 2025-07-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0107_alter_profile_job_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='roles', to='users.menuitem', verbose_name='دسترسی به آیتم\u200cها'),
        ),
    ]
