# Generated by Django 5.2.4 on 2025-07-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0108_jobs_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='شماره تماس'),
        ),
    ]
