# Generated by Django 5.1.1 on 2025-07-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0109_alter_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='user',
        ),
    ]
