# Generated by Django 5.1.1 on 2025-07-28 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0042_remove_cuttingsaw_value_cuttingsaw_image'),
        ('users', '0110_remove_buyer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='coop',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coop_inventory_log', to='StoneFlow.coops'),
        ),
    ]
