# Generated by Django 5.1.1 on 2025-07-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0113_alter_buyerlog_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerlog',
            name='activity_type',
            field=models.CharField(choices=[('order', 'سفارش'), ('call', 'تماس'), ('wahtsapp', 'پیام واتساپ'), ('session', 'جلسات'), ('factors', 'فاکتور ها')], default='order', max_length=20, verbose_name='نوع فعالیت'),
        ),
    ]
