# Generated by Django 5.1.1 on 2025-07-31 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0114_alter_buyerlog_activity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'تماس تلفنی'), ('meeting', 'جلسه'), ('message', 'پیام'), ('email', 'ایمیل'), ('whatsapp', 'واتساپ'), ('note', 'یادداشت'), ('update', 'به\u200cروزرسانی اطلاعات'), ('factors', 'فاکتور ها و خرید')], max_length=20, verbose_name='نوع فعالیت')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فعالیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('next_followup', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پیگیری بعدی')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.buyer', verbose_name='خریدار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'فعالیت خریدار',
                'verbose_name_plural': 'فعالیت\u200cهای خریدار',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='BuyerLog',
        ),
    ]
