# Generated by Django 5.1.1 on 2025-08-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0115_buyeractivity_delete_buyerlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyeractivity',
            name='activity_type',
            field=models.CharField(choices=[('call', 'تماس تلفنی'), ('meeting', 'جلسه'), ('message', 'پیام'), ('email', 'ایمیل'), ('whatsapp', 'واتساپ'), ('note', 'یادداشت'), ('factors', 'فاکتور ها و خرید')], max_length=20, verbose_name='نوع فعالیت'),
        ),
    ]
