# Generated by Django 5.1.1 on 2025-08-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0116_alter_buyeractivity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeractivity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='activity_logos/', verbose_name='لوگو فعالیت'),
        ),
    ]
