# Generated by Django 5.1.1 on 2025-08-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0117_buyeractivity_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
