# Generated by Django 5.1.1 on 2025-08-03 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0118_buyer_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.AddField(
            model_name='buyer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.buyercategory', verbose_name='دسته\u200cبندی خریدار'),
        ),
    ]
