# Generated by Django 5.1.1 on 2025-08-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0119_buyercategory_buyer_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='category',
        ),
        migrations.AddField(
            model_name='buyer',
            name='categories',
            field=models.ManyToManyField(blank=True, to='users.buyercategory', verbose_name='دسته\u200cبندی\u200cهای خریدار'),
        ),
    ]
