# Generated by Django 5.2.3 on 2025-08-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0120_remove_buyer_category_buyer_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyercategory',
            name='color',
            field=models.CharField(default='#cccccc', max_length=10),
        ),
    ]
