# Generated by Django 5.2.3 on 2025-08-03 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0121_buyercategory_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان زیرمنو')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='آیکون (کلاس FontAwesome)')),
                ('url', models.CharField(max_length=200, verbose_name='آدرس URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('parent_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='users.menuitem', verbose_name='منوی والد')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
