# Generated by Django 5.2.3 on 2025-08-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0123_buyeractivity_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyeractivity',
            name='user',
        ),
    ]
