# Generated by Django 5.2.3 on 2025-08-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0125_buyer_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylog',
            name='confirmed_by_buyer',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='coop',
        ),
    ]
