# Generated by Django 5.2.3 on 2025-09-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0127_materialcategory_raw_material_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='users_category', to='users.materialcategory'),
        ),
    ]
