# Generated by Django 5.2.6 on 2025-11-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0128_profile_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='category',
            field=models.CharField(default='عمومی', max_length=100),
        ),
        migrations.AddField(
            model_name='tools',
            name='icon',
            field=models.CharField(default='⚙️', max_length=100),
        ),
        migrations.AddField(
            model_name='tools',
            name='status',
            field=models.CharField(choices=[('ready', 'آماده'), ('dev', 'در حال توسعه')], default='ready', max_length=50),
        ),
    ]
