# Generated by Django 5.2.6 on 2025-11-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0129_tools_category_tools_icon_tools_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='icon',
            field=models.CharField(choices=[('⚙️', '⚙️ تنظیمات'), ('📊', '📊 گزارش / داشبورد'), ('🍽️', '🍽️ غذا / منو'), ('📦', '📦 انبار / کالا'), ('💰', '💰 مالی / هزینه'), ('🧮', '🧮 محاسبات / ابزار'), ('📅', '📅 برنامه\u200cریزی / زمان\u200cبندی'), ('🔧', '🔧 ابزار / تنظیمات فنی'), ('🧾', '🧾 فاکتور / سند'), ('🧠', '🧠 هوش / AI')], default='⚙️', max_length=10, verbose_name='آیکون'),
        ),
    ]
