# Generated by Django 6.0.2 on 2026-02-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0130_alter_tools_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='categories',
        ),
        migrations.AddField(
            model_name='profile',
            name='code_vaset',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد واسط'),
        ),
    ]
