# Generated by Django 6.0.2 on 2026-04-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0131_remove_profile_categories_profile_code_vaset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='describe',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='level',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
