# Generated by Django 5.2.17 on 2026-09-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0132_alter_jobs_describe_alter_jobs_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrawmaterial',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
