# Generated by Django 5.1.1 on 2025-06-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
