# Generated by Django 6.0.2 on 2026-05-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0003_nightlyformmodel_nightlyformhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightlyformmodel',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='nightly_voices/', verbose_name='ویس توضیحات'),
        ),
    ]
