# Generated by Django 6.0.2 on 2026-03-23 10:07

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200, verbose_name='نام')),
                ('l_name', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sms_template',
            name='name',
            field=models.CharField(choices=[('signup', 'ثبت نام'), ('login', 'ورود'), ('close_sandogh', 'بستن صندوق')], max_length=100, verbose_name='نوع قالب پیامک'),
        ),
        migrations.CreateModel(
            name='SMS_Recievers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_person', to='otp_manager.sms_persons', verbose_name='دریافت کننده')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_template', to='otp_manager.sms_template', verbose_name='قالب پیامک')),
            ],
        ),
    ]
