# Generated by Django 6.0.2 on 2026-03-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_manager', '0002_sms_persons_alter_sms_template_name_sms_recievers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_persons',
            name='phone',
            field=models.BigIntegerField(unique=True, verbose_name='شماره تماس'),
        ),
    ]
