# Generated by Django 6.0.2 on 2026-05-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_manager', '0004_alter_sms_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_template',
            name='name',
            field=models.CharField(choices=[('signup', 'ثبت نام'), ('auto_signup', 'ثبت نام اتوماتیک'), ('login', 'ورود'), ('close_sandogh', 'بستن صندوق'), ('night_order', 'سفارش شب')], max_length=100, verbose_name='نوع قالب پیامک'),
        ),
    ]
