# Generated by Django 6.0.6 on 2026-06-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_manager', '0005_alter_sms_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms_template',
            name='name',
            field=models.CharField(choices=[('signup', 'ثبت نام'), ('auto_signup', 'ثبت نام اتوماتیک'), ('login', 'ورود'), ('close_sandogh', 'بستن صندوق'), ('night_order', 'سفارش شب'), ('personel_night_order', 'سفارش به نام پرسنل')], max_length=100, verbose_name='نوع قالب پیامک'),
        ),
    ]
