# Generated by Django 5.1.1 on 2025-06-25 20:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0099_mother_material_image_raw_material_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='coops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.raw_material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
