# Generated by Django 5.1.1 on 2025-06-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coops',
            name='unit',
        ),
    ]
