# Generated by Django 5.1.1 on 2025-06-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0002_remove_coops_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='coops',
            name='state',
            field=models.CharField(choices=[('transport', 'حمل و نقل'), ('warehouse', 'انبار کوپ'), ('accounting', 'حسابداری'), ('warehouse production', 'انبار تولید'), ('production', 'تولید'), ('factory_stock', 'افزودن به انبار کارخانه'), ('customer_order', 'سفارش مشتری'), ('showroom', 'نمایشگاه')], default='transport', max_length=30),
        ),
    ]
