# Generated by Django 5.1.1 on 2025-06-26 11:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0003_coops_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoopStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_state', models.CharField(choices=[('transport', 'حمل و نقل'), ('warehouse', 'انبار کوپ'), ('accounting', 'حسابداری'), ('warehouse production', 'انبار تولید'), ('production', 'تولید'), ('factory_stock', 'افزودن به انبار کارخانه'), ('customer_order', 'سفارش مشتری'), ('showroom', 'نمایشگاه')], max_length=30)),
                ('new_state', models.CharField(choices=[('transport', 'حمل و نقل'), ('warehouse', 'انبار کوپ'), ('accounting', 'حسابداری'), ('warehouse production', 'انبار تولید'), ('production', 'تولید'), ('factory_stock', 'افزودن به انبار کارخانه'), ('customer_order', 'سفارش مشتری'), ('showroom', 'نمایشگاه')], max_length=30)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('coop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='StoneFlow.coops')),
            ],
        ),
    ]
