# Generated by Django 5.1.1 on 2025-06-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0004_coopstatehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='coops',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mining_remittance/'),
        ),
    ]
