# Generated by Django 5.1.1 on 2025-07-03 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0006_carmodel_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoopAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('int', 'عدد صحیح'), ('float', 'عدد اعشاری'), ('str', 'متن')], max_length=10)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CoopAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoneFlow.coopattribute')),
                ('coop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='StoneFlow.coops')),
            ],
        ),
    ]
