# Generated by Django 5.1.1 on 2025-07-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0007_coopattribute_coopattributevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='coopattributevalue',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
