# Generated by Django 5.1.1 on 2025-07-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0008_coopattributevalue_default_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coopattributevalue',
            name='default_value',
        ),
        migrations.AddField(
            model_name='coopattribute',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
