# Generated by Django 5.1.1 on 2025-07-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0009_remove_coopattributevalue_default_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopattribute',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
