# Generated by Django 5.1.1 on 2025-07-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0010_alter_coopattribute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopattribute',
            name='label',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='coopattribute',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
