# Generated by Django 5.1.1 on 2025-07-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0011_alter_coopattribute_label_alter_coopattribute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coopattribute',
            name='step',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مرحله اول'), (2, 'مرحله دوم'), (3, 'مرحله سوم')], default=1, verbose_name='مرحله نمایش'),
        ),
    ]
