# Generated by Django 5.1.1 on 2025-07-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0012_coopattribute_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='coopattribute',
            name='select_options',
            field=models.TextField(blank=True, help_text='مقادیر منو را با کاما جدا کنید (مثلاً: کوچک,متوسط,بزرگ)', null=True),
        ),
        migrations.AlterField(
            model_name='coopattribute',
            name='field_type',
            field=models.CharField(choices=[('int', 'عدد صحیح'), ('float', 'عدد اعشاری'), ('str', 'متن'), ('select', 'منوی کشویی')], max_length=10),
        ),
    ]
