# Generated by Django 5.1.1 on 2025-07-05 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0014_step_stepaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopattribute',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoneFlow.step', verbose_name='مرحله نمایش'),
        ),
    ]
