# Generated by Django 5.1.1 on 2025-07-05 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0015_alter_coopattribute_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopstatehistory',
            name='new_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_history', to='StoneFlow.step'),
        ),
        migrations.AlterField(
            model_name='coopstatehistory',
            name='previous_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_history', to='StoneFlow.step'),
        ),
    ]
