# Generated by Django 5.1.1 on 2025-07-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0017_remove_coopstatehistory_new_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coopstatehistory',
            name='changed_at',
        ),
        migrations.RemoveField(
            model_name='coopstatehistory',
            name='changed_by',
        ),
    ]
