# Generated by Django 5.1.1 on 2025-07-05 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0019_coopstatehistory_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coops',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coops_step', to='StoneFlow.step'),
        ),
    ]
