# Generated by Django 5.1.1 on 2025-07-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0023_alter_coopattribute_field_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام گروه ویژگی\u200cها')),
                ('attributes', models.ManyToManyField(related_name='groups', to='StoneFlow.coopattribute', verbose_name='ویژگی\u200cها')),
            ],
        ),
    ]
