# Generated by Django 5.1.1 on 2025-07-11 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0024_attributegroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coopattributevalue',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CoopAttributeValue_submissions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
