# Generated by Django 5.1.1 on 2025-07-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0025_coopattributevalue_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopattribute',
            name='field_type',
            field=models.CharField(choices=[('int', 'عدد صحیح'), ('float', 'عدد اعشاری'), ('str', 'متن'), ('select', 'منوی کشویی'), ('bool', 'چک\u200cباکس'), ('image', 'تصویر'), ('material', 'ماده اولیه'), ('warehouse', 'انبار'), ('multi_select', 'چک\u200cباکس چندتایی'), ('date', 'تاریخ (شمسی)')], max_length=20),
        ),
    ]
