# Generated by Django 5.1.1 on 2025-07-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0026_alter_coopattribute_field_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cutting_factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('city', models.CharField(max_length=100, unique=True, verbose_name='شهر')),
            ],
        ),
    ]
