# Generated by Django 5.1.1 on 2025-07-13 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0027_cutting_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopattribute',
            name='field_type',
            field=models.CharField(choices=[('int', 'عدد صحیح'), ('float', 'عدد اعشاری'), ('str', 'متن'), ('select', 'منوی کشویی'), ('bool', 'چک\u200cباکس'), ('image', 'تصویر'), ('material', 'ماده اولیه'), ('warehouse', 'انبار'), ('Cutting_factory', 'کارخانه برش اره'), ('multi_select', 'چک\u200cباکس چندتایی'), ('date', 'تاریخ (شمسی)')], max_length=20),
        ),
        migrations.CreateModel(
            name='CuttingSaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenght', models.FloatField(verbose_name='طول')),
                ('width', models.FloatField(verbose_name='عرض')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='توضیحات')),
                ('coop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CuttingSaw_values', to='StoneFlow.coops')),
            ],
        ),
    ]
