# Generated by Django 5.1.1 on 2025-07-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0028_alter_coopattribute_field_type_cuttingsaw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuttingsaw',
            old_name='lenght',
            new_name='length',
        ),
        migrations.AlterField(
            model_name='coopattribute',
            name='field_type',
            field=models.CharField(choices=[('int', 'عدد صحیح'), ('float', 'عدد اعشاری'), ('str', 'متن'), ('select', 'منوی کشویی'), ('bool', 'چک\u200cباکس'), ('image', 'تصویر'), ('material', 'ماده اولیه'), ('warehouse', 'انبار'), ('Cutting_factory', 'کارخانه برش اره'), ('CuttingSaw', 'موارد برش اره'), ('multi_select', 'چک\u200cباکس چندتایی'), ('date', 'تاریخ (شمسی)')], max_length=20),
        ),
    ]
