# Generated by Django 5.1.1 on 2025-07-13 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0029_rename_lenght_cuttingsaw_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingAround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(verbose_name='طول')),
                ('width', models.FloatField(verbose_name='عرض')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('serial', models.PositiveIntegerField(verbose_name='شماره سریال')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='توضیحات')),
                ('coop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CuttingAround_values', to='StoneFlow.coops')),
            ],
        ),
    ]
