# Generated by Django 5.2.4 on 2025-07-19 16:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0032_coops_is_active_coopdeleterequest'),
        ('users', '0101_remove_buyerattribute_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coopattributevalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 19, 16, 14, 39, 790624)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coopattributevalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coopattribute',
            name='field_type',
            field=models.CharField(choices=[('int', 'عدد صحیح'), ('float', 'عدد اعشاری'), ('str', 'متن'), ('select', 'منوی کشویی'), ('bool', 'چک\u200cباکس'), ('image', 'تصویر'), ('material', 'ماده اولیه'), ('warehouse', 'انبار'), ('Cutting_factory', 'کارخانه برش اره'), ('CuttingSaw', 'موارد برش اره'), ('CuttingAround', 'موارد دور بور شده'), ('multi_select', 'چک\u200cباکس چندتایی'), ('date', 'تاریخ (شمسی)'), ('price', 'قیمت'), ('show_attr', 'نمایش ویژگی دیگر')], max_length=20),
        ),
        migrations.CreateModel(
            name='PreInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.buyer', verbose_name='نام مشتری')),
            ],
        ),
        migrations.CreateModel(
            name='PreInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت واحد')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='تخفیف')),
                ('coop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoneFlow.coops', verbose_name='کوپ انتخابی')),
                ('pre_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='StoneFlow.preinvoice')),
            ],
        ),
    ]
