# Generated by Django 5.2.4 on 2025-07-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0033_coopattributevalue_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coops',
            name='is_sell',
            field=models.BooleanField(default=False),
        ),
    ]
