# Generated by Django 5.2.4 on 2025-07-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0034_coops_is_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingsaw',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuttingsaw',
            name='is_sell',
            field=models.BooleanField(default=False),
        ),
    ]
