# Generated by Django 5.2.4 on 2025-07-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0035_cuttingsaw_is_active_cuttingsaw_is_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingsaw',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Stone/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='cuttingsaw',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت'),
        ),
    ]
