# Generated by Django 5.2.4 on 2025-07-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0036_cuttingsaw_image_cuttingsaw_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttingsaw',
            name='price',
        ),
        migrations.AddField(
            model_name='cuttingsaw',
            name='production_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت تولیدی'),
        ),
        migrations.AddField(
            model_name='cuttingsaw',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت فروش'),
        ),
    ]
