# Generated by Django 5.2.4 on 2025-07-23 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0037_remove_cuttingsaw_price_cuttingsaw_production_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttingsaw',
            name='production_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True, verbose_name='قیمت تولیدی'),
        ),
        migrations.AlterField(
            model_name='cuttingsaw',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True, verbose_name='قیمت فروش'),
        ),

    ]
