# Generated by Django 5.2.4 on 2025-07-23 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0038_alter_cuttingsaw_production_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinvoiceitem',
            name='coop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoneFlow.cuttingsaw', verbose_name='کوپ انتخابی'),
        ),
    ]
