# Generated by Django 5.1.1 on 2025-07-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0039_alter_preinvoiceitem_coop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttingsaw',
            name='production_price',
        ),
        migrations.RemoveField(
            model_name='cuttingsaw',
            name='sell_price',
        ),
    ]
