# Generated by Django 5.1.1 on 2025-07-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0040_remove_cuttingsaw_production_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttingsaw',
            name='image',
        ),
        migrations.AddField(
            model_name='cuttingsaw',
            name='value',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='coopattributevalue',
            name='value',
            field=models.CharField(max_length=5000),
        ),
    ]
