# Generated by Django 5.1.1 on 2025-07-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0041_remove_cuttingsaw_image_cuttingsaw_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttingsaw',
            name='value',
        ),
        migrations.AddField(
            model_name='cuttingsaw',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cuttingSaw/'),
        ),
    ]
