# Generated by Django 5.1.1 on 2025-07-31 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0042_remove_cuttingsaw_value_cuttingsaw_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinvoiceitem',
            name='coop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoneFlow.coops', verbose_name='کوپ انتخابی'),
        ),
    ]
