# Generated by Django 5.1.1 on 2025-08-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0043_alter_preinvoiceitem_coop'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinvoiceitem',
            name='is_sell',
            field=models.BooleanField(default=False),
        ),
    ]
