# Generated by Django 5.1.1 on 2025-08-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0044_preinvoiceitem_is_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinvoice',
            name='is_sell',
            field=models.BooleanField(default=False),
        ),
    ]
