# Generated by Django 5.1.1 on 2025-07-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines', '0002_mine_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='mine',
            name='mine_type',
            field=models.CharField(choices=[('surface', 'معدن زمینی'), ('store', 'انبار کوپ')], default='surface', max_length=20, verbose_name='نوع معدن'),
        ),
        migrations.AlterField(
            model_name='mine',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
    ]
