# Generated by Django 5.1.1 on 2025-04-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام حساب')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='شماره حساب')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام بانک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('message', models.TextField()),
            ],
        ),
    ]
