# Generated by Django 6.0.6 on 2026-09-16 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowStockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='کل داده ورودی به صورت JSON')),
                ('source', models.CharField(blank=True, max_length=100)),
                ('total_items', models.IntegerField(default=0)),
                ('low_stock_count', models.IntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('sender_timestamp', models.CharField(blank=True, max_length=100)),
                ('received_from_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.apikey')),
            ],
            options={
                'verbose_name': 'گزارش کمبود موجودی',
                'verbose_name_plural': 'گزارش\u200cهای کمبود موجودی',
                'ordering': ['-received_at'],
            },
        ),
    ]
