# Generated by Django 6.0.6 on 2026-09-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lowstockreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowstockreport',
            name='critical_count',
            field=models.IntegerField(default=0, help_text='اقلام با وضعیت danger', verbose_name='تعداد اقلام بحرانی'),
        ),
        migrations.AddField(
            model_name='lowstockreport',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='خوانده شده'),
        ),
        migrations.AddField(
            model_name='lowstockreport',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AddField(
            model_name='lowstockreport',
            name='sender_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP فرستنده'),
        ),
        migrations.AddField(
            model_name='lowstockreport',
            name='shortage_percent',
            field=models.FloatField(default=0, help_text='درصد اقلامی که کمبود دارند نسبت به کل', verbose_name='درصد کمبود'),
        ),
        migrations.AddField(
            model_name='lowstockreport',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewed', 'بررسی شده'), ('resolved', 'حل شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='lowstockreport',
            name='total_shortage',
            field=models.FloatField(default=0, help_text='مجموع کمبود همه اقلام', verbose_name='مجموع کمبود'),
        ),
        migrations.AddField(
            model_name='lowstockreport',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='lowstockreport',
            name='warning_count',
            field=models.IntegerField(default=0, help_text='اقلام با وضعیت warning', verbose_name='تعداد اقلام هشدار'),
        ),
    ]
