# Generated by Django 5.1.1 on 2025-08-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='embed_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
