# Generated by Django 5.1.1 on 2025-08-18 21:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_person_embed_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='DetectedPersons',
        ),
    ]
