# Generated by Django 5.2.3 on 2025-08-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_rename_person_detectedpersons'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeatureName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('object_detection', 'Object Detection'), ('face_recognition', 'Face Recognition'), ('mask_detection', 'Mask Detection'), ('other', 'Other')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='ai_features',
            field=models.ManyToManyField(blank=True, related_name='cameras', to='cameras.aifeaturename'),
        ),
    ]
