# Generated by Django 5.2.3 on 2025-09-08 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_aifeaturename_camera_ai_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('other_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aifeaturename',
            name='name',
            field=models.CharField(choices=[('object_detection', 'Object Detection'), ('face_recognition', 'Face Recognition'), ('mask_detection', 'Mask Detection'), ('face_detection', 'Face Detection'), ('other', 'Other')], max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='cameras.person')),
            ],
        ),
    ]
