# Generated by Django 5.2.3 on 2025-09-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_person_created_at_person_updated_at_persondetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_unkonwn',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
