# Generated by Django 6.0.6 on 2026-06-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_bank_bankcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcard',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
