# Generated by Django 5.2.6 on 2025-11-21 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلاً: روتر اصلی شرکت', max_length=200)),
                ('category', models.CharField(choices=[('network', 'شبکه'), ('server', 'سرور'), ('app', 'نرم\u200cافزار'), ('other', 'سایر')], default='network', max_length=50)),
                ('system_address', models.CharField(blank=True, help_text='IP یا آدرس سیستم', max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(help_text='رمز عبور (فعلاً ساده ذخیره می\u200cکنیم)', max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='vault_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
