# Generated by Django 5.2.6 on 2025-11-21 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordentry',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='passwordentry',
            name='password',
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='encrypted_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='system_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='PasswordAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vault_files/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='vault.passwordentry')),
            ],
        ),
    ]
