# Generated by Django 6.0.6 on 2026-06-09 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0132_alter_jobs_describe_alter_jobs_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('destination', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_transfer', to='users.raw_material')),
            ],
            options={
                'verbose_name': 'انتقال مواد اولیه',
                'verbose_name_plural': 'انتقالات مواد اولیه',
            },
        ),
    ]
