# Generated by Django 6.0.6 on 2026-06-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterialtransfer',
            old_name='mother',
            new_name='material',
        ),
    ]
