# Generated by Django 5.2.17 on 2026-09-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldoutstatus',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
