# Generated by Django 5.2.17 on 2026-09-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_soldoutstatus_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldoutstatus',
            name='is_new',
        ),
    ]
