# Generated by Django 5.2.3 on 2025-10-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factnum', models.CharField(max_length=1000, unique=True)),
                ('dat', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=22)),
                ('kname', models.CharField(max_length=1000)),
                ('tel', models.CharField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
