# Generated by Django 5.2.3 on 2026-01-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalysis', '0002_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='nahveh',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
