# Generated by Django 5.2.3 on 2026-02-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalysis', '0003_invoice_nahveh_invoice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
