# Generated by Django 6.0.2 on 2026-02-23 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalysis', '0004_invoice_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='anaam',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='peyk',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online'), ('nesiye', 'Nesiye')], max_length=20)),
                ('amount', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='DataAnalysis.invoice')),
            ],
        ),
    ]
