# Generated by Django 6.0.2 on 2026-03-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalysis', '0005_invoice_anaam_invoice_peyk_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online'), ('nesiye', 'Nesiye'), ('anaam', 'Anaam')], max_length=20),
        ),
    ]
