# Generated by Django 6.0.2 on 2026-03-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalysis', '0007_invoice_hazine_pryk_invoice_mablagh_pos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='hazine_pryk',
            new_name='hazine_peyk',
        ),
        migrations.AddField(
            model_name='invoice',
            name='mandeh',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
