# Generated by Django 6.0.2 on 2026-03-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalysis', '0008_rename_hazine_pryk_invoice_hazine_peyk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='nonaghdi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
