# Generated by Django 6.0.2 on 2026-05-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalysis', '0009_invoice_nonaghdi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('pos', 'Pos'), ('online', 'Online'), ('nesiye', 'Nesiye'), ('anaam', 'Anaam')], max_length=20),
        ),
    ]
