# Generated by Django 5.2.15 on 2026-06-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalysis', '0010_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(unique=True),
        ),
    ]
