# Generated by Django 6.0.2 on 2026-06-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalysis', '0012_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='unique_invoice_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(),
        ),
    ]
