# Generated by Django 6.0.6 on 2026-09-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalysis', '0013_invoice_unique_invoice_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, unique=True)),
                ('foodsoft_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sepdar_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
    ]
