# Generated by Django 6.0.6 on 2026-09-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalysis', '0014_fooditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='sepdar_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
